### ISSUE TITLE
Text Area not updating on New File creation

### ISSUE THREAD

**Issue by MachinationGames** [MidooriTV/UnityNotepad#1]
When creating a new file with unsaved changes, the text area does not update to reflect the new file, even though the dropdown menu indicates that you are in the new file.

**Comment by MachinationGames** [comment]
Latest merge no longer updates the Text Area even with the file saved.

**Comment by neutralparadoxdev** [comment]
Its funny. I thought it was gone. 

Now I am experiencing it.

The issue I see on my side is EditorGuiLayout.TextArea() does not automatically reflect on the screen. This happens only occasionally (though, it can occasionally happen consistently). If you wait, or potentially swap tabs), it will update to reflect an empty file.

So, I believe there is a bit of thread contention where the OnGui Completes successfully, but the window does not reflect it.

**Comment by neutralparadoxdev** [comment]
Ok, It might be related to whether the item is focused. 

If it is unfocused, it will immediately updated.

If it is focused, it will maintain state with the existing text and wont update to empty until unfocused. It will also update with the prior text + new input if new characters is provided. If no new input is provided (such as moving cursor), it will update to empty string once focus is lost.

**Comment by MachinationGames** [comment]
Check the latest release. I fixed the new issue after merging the code you provided. Also extracted NotepadModel to it's own class. Only issue remains is the original one that I'm still unable to figure out
